### ISSUE TITLE
Create kubernetes nginx deployment

### ISSUE THREAD

**Issue by grimpy** [0-complexity/openvcloud_installer#27]
We need to make sure we can generate the followign [file](https://git.aydo.com/binary/openvcloud_ssloffloader/blob/2.1/ovc)
Previously this was done by the [ssloffloader](https://github.com/0-complexity/openvcloud_ays/blob/master/ssloffloader/actions.py) ays

## Variables used and where to get them:
`master.ipadress` : cb_master < name of portal pod
`locations`: contains dictExample: 
```yaml
be-g8-3:
 - cpu-01-mgmtip:2001
 - cpu-02-mgmtip:2001
ovs-be-g8-3:
 - stor-01-mgmtip:2001
 - stor-02-mgmtip:2001
```
`host`: our fqdn Example: be-g8-3.demo.greenitglobe.com
`domain`: Exmaple: `demo.greentiglobe.com`

We also need to make sure the references to the ceriticates are updated and pointing to the files locally accessible on the nginx container
see `ssl_certificate /opt/nginx/cfg/ssl/{{ssl.novnc}}.crt;` in the config
